### ISSUE TITLE
Plugin fails when using schema stitching

### ISSUE THREAD

**Issue by petetnt** [mattbretl/postgraphile-plugin-upload-field#2]
First of all, thanks for this great plugin!

Not quite sure if I am doing something wrong, but at least I assume that the cause is the following: https://github.com/apollographql/graphql-tools/issues/659

I have multiple schemas stitched and I use `makeExtendSchemaPlugin` to extend my Postgraphile instance. My custom schema looks like this:

```js
const types = `
  extend type Mutation {
    bulkImport(input: BulkImportInput!): BulkUploadResponse!
  }

  input BulkImportInput {
    file: [Upload]
  }

  type BulkUploadResponse {
    status: String
  }
`;
```

And my mutation looks like:

```graphql
  mutation uploadFile($input: BulkImportInput!) {
    bulkImport(input: $input) {
      status
    }
  }
```

But the mutation fails with the following error:

```json
    {
      "message": "Cannot read property 'bulkImport' of null",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "bulkImport"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "errors": [
            {
              "message": "Cannot read property 'bulkImport' of null",
              "locations": [],
              "path": [
                "bulkImport"
              ]
            }
          ],
          "stacktrace": [
            "Error: Cannot read property 'bulkImport' of null",
            "    at new CombinedError (/node_modules/graphql-tools/dist/stitching/errors.js:82:28)",
            "    at Object.checkResultAndHandleErrors (/node_modules/graphql-tools/dist/stitching/errors.js:98:15)",
            "    at CheckResultAndHandleErrors.transformResult (/graphql-tools/dist/transforms/CheckResultAndHandleErrors.js:9:25)",
            "    at /node_modules/graphql-tools/dist/transforms/transforms.js:18:54",
            "    at Array.reduce (<anonymous>)",
            "    at applyResultTransforms (/node_modules/graphql-tools/dist/transforms/transforms.js:17:23)",
            "    at node_modules/graphql-tools/dist/stitching/delegateToSchema.js:97:50",
            "    at step (/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:31:23)",
            "    at Object.next (/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:12:53)",
            "    at fulfilled (/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:3:58)",
            "    at <anonymous>",
            "    at process._tickCallback (internal/process/next_tick.js:188:7)"
          ]
        } 
```

Adding a dummy query to the schema where `Upload` was used didn't help, so it might be so that needs to be defined in the plugin itself 🤔

**Comment by petetnt** [comment]
Actually I'll close this 'til I'll debug this is a bit further

**Comment by petetnt** [comment]
Blargh, it was unrelated (resolver name mismatch) but the issue was confusingly similar. Sorry & thanks!
